export const LOGIN_USER_TYPE = "LOGIN_USER_TYPE";
export const LOGIN_USER_SAGA_TYPE = "LOGIN_USER_SAGA_TYPE";

export const REGISTER_USER_TYPE = "REGISTER_USER_TYPE";
export const REGISTER_USER_SAGA_TYPE = "REGISTER_USER_SAGA_TYPE";
