export const LOGIN_USER_TYPE = "LOGIN_USER_TYPE";
export const LOGIN_USER_SAGA_TYPE = "LOGIN_USER_SAGA_TYPE";

export const REGISTER_USER_TYPE = "REGISTER_USER_TYPE";
export const REGISTER_USER_SAGA_TYPE = "REGISTER_USER_SAGA_TYPE";

export const GET_PROFILE_USER_TYPE = "GET_PROFILE_USER_TYPE";
export const GET_PROFILE_USER_SAGA_TYPE = "GET_PROFILE_USER_SAGA_TYPE";

// Admin Type
export const LOGIN_ADMIN_TYPE = "LOGIN_ADMIN_TYPE";
export const LOGIN_ADMIN_SAGA_TYPE = "LOGIN_ADMIN_SAGA_TYPE";

export const GET_USER_LIST_ADMIN_TYPE = "GET_USER_LIST_ADMIN_TYPE";
export const GET_USER_LIST_ADMIN_SAGA_TYPE = "GET_USER_LIST_ADMIN_SAGA_TYPE";

export const ADD_USER_ADMIN_TYPE = "ADD_USER_ADMIN_TYPE";
export const ADD_USER_ADMIN_SAGA_TYPE = "ADD_USER_ADMIN_SAGA_TYPE";

export const DELETE_USER_SAGA_TYPE = "DELETE_USER_SAGA_TYPE";

export const FIND_USER_ADMIN_TYPE = "FIND_USER_ADMIN_TYPE";
export const FIND_USER_ADMIN_SAGA_TYPE = "FIND_USER_ADMIN_SAGA_TYPE";

export const EDIT_USER_ADMIN_TYPE = "EDIT_USER_ADMIN_TYPE";
export const EDIT_USER_ADMIN_SAGA_TYPE = "EDIT_USER_ADMIN_SAGA_TYPE";
