export const GET_THEATER_TYPE = "GET_THEATER_TYPE";
export const GET_THEATER_SAGA_TYPE = "GET_THEATER_SAGA_TYPE";

export const GET_INFO_THEATER_TYPE = "GET_INFO_THEATER_TYPE";
export const GET_INFO_THEATER_SAGA_TYPE = "GET_INFO_THEATER_SAGA_TYPE";
