export const GET_THEATER_TYPE = "GET_THEATER_TYPE";
export const GET_THEATER_SAGA_TYPE = "GET_THEATER_SAGA_TYPE";

export const GET_INFO_THEATER_TYPE = "GET_INFO_THEATER_TYPE";
export const GET_INFO_THEATER_SAGA_TYPE = "GET_INFO_THEATER_SAGA_TYPE";

export const GET_FILM_SHOWTIME_INFOMATION_TYPE =
  "GET_FILM_SHOWTIME_INFOMATION_TYPE";
export const GET_FILM_SHOWTIME_INFOMATION_SAGA_TYPE =
  "GET_FILM_SHOWTIME_INFOMATION_SAGA_TYPE";

export const GET_FILM_SHOWTIME_INFOMATION_THEATER_TYPE =
  "GET_FILM_SHOWTIME_INFOMATION_THEATER_TYPE";
export const GET_FILM_SHOWTIME_INFOMATION_THEATER_SAGA_TYPE =
  "GET_FILM_SHOWTIME_INFOMATION_THEATER_SAGA_TYPE";
