// Lấy danh sách phim
export const GET_MOVIE_LIST_TYPE = "GET_MOVIE_LIST_TYPE";
export const GET_MOVIE_LIST_SAGA_TYPE = "GET_MOVIE_LIST_SAGA_TYPE";

export const GET_DETAIL_MOVIE_TYPE = "GET_DETAIL_MOVIE_TYPE";
export const GET_DETAIL_MOVIE_SAGA_TYPE = "GET_DETAIL_MOVIE_SAGA_TYPE";
