// Lấy danh sách phim
export const GET_MOVIE_LIST_TYPE = "GET_MOVIE_LIST_TYPE";
export const GET_MOVIE_LIST_SAGA_TYPE = "GET_MOVIE_LIST_SAGA_TYPE";

// Lấy chi tiết phim
export const GET_DETAIL_MOVIE_TYPE = "GET_DETAIL_MOVIE_TYPE";
export const GET_DETAIL_MOVIE_SAGA_TYPE = "GET_DETAIL_MOVIE_SAGA_TYPE";

// Thêm phim

export const CREATE_MOVIE_TYPE = "CREATE_MOVIE_TYPE";
export const CREATE_MOVIE_SAGA_TYPE = "CREATE_MOVIE_SAGA_TYPE";

// Xóa phim

export const DELETE_MOVIE_TYPE = "DELETE_MOVIE_TYPE";
export const DELETE_MOVIE_SAGA_TYPE = "DELETE_MOVIE_SAGA_TYPE";

// Sửa phim

export const EDIT_MOVIE_TYPE = "EDIT_MOVIE_TYPE";
export const EDIT_MOVIE_SAGA_TYPE = "EDIT_MOVIE_SAGA_TYPE";
