export const GET_LIST_CHAIR_TYPE = "GET_LIST_CHAIR_TYPE";
export const GET_LIST_CHAIR_SAGA_TYPE = "GET_LIST_CHAIR_SAGA_TYPE";

export const BOOKING_TYPE = "BOOKING_TYPE";
export const BOOKING_SAGA_TYPE = "BOOKING_SAGA_TYPE";

export const CREATE_SHOW_TIME_TYPE = "CREATE_SHOW_TIME_TYPE";
export const CREATE_SHOW_TIME_SAGA_TYPE = "CREATE_SHOW_TIME_SAGA_TYPE";
